version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.openrewrite:*"
      - dependency-name: "org.openrewrite.rewrite:*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"