name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        java: [ '8', '11', '17' ]
        distribution: [ 'zulu', 'temurin' ]
        os: [ 'ubuntu-20.04' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.3.5
    - name: Gradle wrapper validation
      uses: gradle/wrapper-validation-action@v1.0.4
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
        cache: 'gradle'
    - name: print Java version
      run: java -version
    - name: Build
      run: ./gradlew clean build jacocoTestReport jacocoTestCoverageVerification
