name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        java: [ '8', '11', '13', '14', '15', '16' ]
        distribution: [ 'zulu', 'adopt' ]
        os: [ 'ubuntu-20.04' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Gradle wrapper validation
      uses: gradle/wrapper-validation-action@v1.0.3
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
    - name: print Java version
      run: java -version
    - uses: actions/cache@v2.1.6
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build
      run: ./gradlew clean build jacocoTestReport jacocoTestCoverageVerification
