name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'gradle/**'
      - 'README.md'

jobs:
  release:
    runs-on: 'ubuntu-20.04'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0' # will fetch the entire history
    - name: Gradle wrapper validation
      uses: gradle/wrapper-validation-action@v1.0.4
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 8
    - name: print Java version
      run:  java -version
    - name: print GITHUB_REF
      run:  echo GITHUB_REF=${GITHUB_REF}
    - name: Branch name
      run:  echo running on branch ${GITHUB_REF##*/}
    - name: Gradle ciPerformRelease
      run:  ./gradle clean build && ./gradlew publishToSonatype closeAndReleaseStagingRepository githubRelease
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NEXUS_TOKEN_USER: ${{ secrets.NEXUS_TOKEN_USER }}
        NEXUS_TOKEN_PWD: ${{ secrets.NEXUS_TOKEN_PWD }}
        PGP_KEY: ${{secrets.PGP_KEY}}
        PGP_PWD: ${{secrets.PGP_PWD}}
