name: Release

on: workflow_dispatch

jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Gradle wrapper validation
      uses: gradle/wrapper-validation-action@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: print Java version
      run:  java -version
    - name: Branch name
      run:  echo running on branch ${GITHUB_REF##*/}
    - name: Gradle ciPerformRelease
      run:  ./gradlew build -s && ./gradlew ciPerformRelease -s
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TRAVIS_BRANCH: ${GITHUB_REF##*/}
